services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_TELEGRAM_BOT_TOKEN: ${VITE_TELEGRAM_BOT_TOKEN}
        VITE_TELEGRAM_CHAT_ID: ${VITE_TELEGRAM_CHAT_ID}
    container_name: portfolio-web
    ports:
      - "8080:80"
    restart: unless-stopped
